### ISSUE TITLE
[Bug]: Client crash when attempt to use End Cake

### ISSUE THREAD

**Issue by Gbergz** [Mrbysco/TelePastries#19]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.2.17

### Minecraft version

1.20.1

### Mod version

0.8.3

### Java version

17

### Issue Description

On a local multiplayer server; Not tested in SP.
Client crashes when attempting to use the End Cake. Player does not get teleported, instead crashes.

Pretty sure it's a crossmod interaction issue with The Aether. 
It might not be because of this mod, reporting either way to make sure.

Modpack: https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7
(No additional mods from base modpack: v1.4.0.)

### Crash Report

https://gist.githubusercontent.com/Gbergz/07c575eb49a2890c550c78eba01e1c78/raw/5e84e2da703622a61c745b48d9965bff1e1f689b/gistfile1.txt

**Comment by bconlon1** [comment]
Aether Dev here, from debugging with the help of someone else, it seems like this crash might be occurring because of the call to `ForgeHooks#onTravelToDimension` at https://github.com/Mrbysco/TelePastries/blob/8f39cba79f7baa4213d22f4ac57928a6c27e3135/src/main/java/com/mrbysco/telepastries/blocks/cake/BlockCakeBase.java#L155 not being limited to the server side. Forge on its own only ever posts the `EntityTravelToDimension` event from the server, so the Aether code that uses this event was written with the assumption that it would never be called on the client. The crash seems to be occurring basically because one of our server->client packets is being sent from the client instead, so the server value within PacketDistributor is null. I'll implement a fix on my end since it'd be a good safety check to guarantee the packets can only run on the server side, but it'd probably be good for TelePastries to fix this as well to avoid other potential incompatibilities.

**Comment by Mrbysco** [comment]
See https://github.com/Mrbysco/TelePastries/commit/719d6dee020e5a86ff4b7676886f930428f16248
